import { ClinicalCaseData } from '../types/clinicalCase';
import { sampleTacDataUrl, sampleRxDataUrl } from './sampleImages';

export const createEmptyCase = (): ClinicalCaseData => ({
  institution: 'ORDEM DOS MÉDICOS DE MOÇAMBIQUE',
  subInstitution: 'COLÉGIO DE NEUROCIRURGIA',
  hospital: 'HOSPITAL CENTRAL DE NAMPULA',
  service: 'SERVIÇO DE NEUROCIRURGIA',
  tipoEvento: 'Jornadas Científicas do Hospital Central de Nampula',

  nome: '',
  nid: '',
  sexo: '',
  idade: '',
  raca: '',
  estadoCivil: '',
  naturalidade: '',
  residencia: '',
  profissao: '',
  localTrabalho: '',
  provenienteDe: '',
  emData: '',
  historiaFornecidaPor: '',
  servicoProveniencia: '',

  motivoInternamento: '',
  historiaDoencaActual: '',

  revisaoSistemas: {
    respiratorio: {
      tosse: { checked: false, observation: '' },
      expectoracao: { checked: false, observation: '' },
      dorToracica: { checked: false, observation: '' },
      dispneia: { checked: false, observation: '' },
      dpnOrtopneia: { checked: false, observation: '' },
      palpitacoes: { checked: false, observation: '' },
      suoresNocturnos: { checked: false, observation: '' },
      pieira: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
    },
    sistemaNervoso: {
      convulsoes: { checked: false, observation: '' },
      sincope: { checked: false, observation: '' },
      cefaleias: { checked: false, observation: '' },
      disturbiosVisuais: { checked: false, observation: '' },
      disturbiosSensibilidade: { checked: false, observation: '' },
      fraquezaMuscular: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
      outros2: { checked: false, observation: '' },
    },
    gastrointestinal: {
      vomitos: { checked: false, observation: '' },
      hematemeses: { checked: false, observation: '' },
      obstipacao: { checked: false, observation: '' },
      pirose: { checked: false, observation: '' },
      enfartamentoPosPrandial: { checked: false, observation: '' },
      flatulencia: { checked: false, observation: '' },
      dorAbdominal: { checked: false, observation: '' },
      ictericia: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
      outros2: { checked: false, observation: '' },
    },
    genitourinario: {
      disuria: { checked: false, observation: '' },
      polaquiuria: { checked: false, observation: '' },
      hematuria: { checked: false, observation: '' },
      incontinenciaUrinaria: { checked: false, observation: '' },
      corrimentoUretralVaginal: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
    },
    hemolinfopoetico: {
      anomaliasCoagulacao: { checked: false, observation: '' },
      anemias: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
    },
    caracterizacaoSintomas: '',
  },

  historiaPregressa: '',
  historiaPessoalSocial: '',
  historiaGinecoObstetrica: '',
  historiaFamiliar: '',

  estadoGeral: '',
  idadeAparente: '',
  glasgowOcular: '',
  glasgowVerbal: '',
  glasgowMotor: '',
  glasgowTotal: '',
  pele: '',
  mucosas: '',
  edemas: '',
  linfadenopatia: '',
  frequenciaCardiaca: '',
  frequenciaRespiratoria: '',
  pulsoRadial: '',
  tensaoArterial: '',
  temperaturaAxilar: '',
  spO2: '',
  peso: '',
  altura: '',
  imc: '',
  outrosExameGeral: '',

  cabecaFacies: '',
  cabecaOlhos: '',
  cabecaNariz: '',
  cabecaBoca: '',
  cabecaOrofaringe: '',
  cabecaOuvidos: '',
  cabecaOutros: '',

  pescocoForma: '',
  pescocoDimensoes: '',
  pescocoMobilidade: '',
  pescocoPosicaoTraqueia: '',
  pescocoPVJ: '',
  pescocoTiroide: '',
  pescocoOutros: '',

  semiologiaRespInspecao: '',
  semiologiaRespPalpacao: '',
  semiologiaRespPercussao: '',
  semiologiaRespAuscultacao: '',

  semiologiaCardInspecao: '',
  semiologiaCardPalpacao: '',
  semiologiaCardPercussao: '',
  semiologiaCardAuscultacao: '',

  mamasAxilasInspecao: '',
  mamasAxilasPalpacao: '',

  abdomenInspecao: '',
  abdomenPalpacao: '',
  abdomenPercussao: '',
  abdomenAuscultacao: '',
  abdomenManobras: '',

  genitaisInspecao: '',
  genitaisPalpacao: '',
  genitaisPercussao: '',
  genitaisAuscultacao: '',
  genitaisUrina: '',

  proctologicoPosicao: '',
  proctologicoInspecao: '',
  proctologicoPalpacao: '',

  ginecologicoPosicao: '',
  ginecologicoInspecao: '',
  ginecologicoPalpacao: '',

  membrosSupInspecao: '',
  membrosSupPalpacao: '',
  membrosSupAuscultacao: '',
  membrosSupManobras: '',

  membrosInfInspecao: '',
  membrosInfPalpacao: '',
  membrosInfAuscultacao: '',
  membrosInfManobras: '',

  estadoMental: '',
  linguagem: '',
  par1: '',
  par2: '',
  fundoscopia: '',
  pares3_4_6: '',
  par5: '',
  par7: '',
  par8: '',
  pares9_10: '',
  par11: '',
  par12: '',
  tonusMuscular: '',
  forcaMuscular: '',
  coordenacaoMarcha: '',
  sensibilidade: '',
  reflexos: '',
  sinaisMeningeos: '',

  resumo: '',
  diagnosticosSindromicos: '',
  diagnosticosEtiologicos: '',
  diagnosticosTopograficos: '',

  meiosAuxiliares: '',
  attachedImages: [],

  diagnosticosDiferenciais: '',
  diagnosticosDefinitivos: '',
  propostaTerapeutica: '',
  prognostico: '',

  elaboradoPor: '',
  mrNc: '',
  corrigidoPor: '',
  comentariosFinais: '',
});

export const sampleCaseData: ClinicalCaseData = {
  institution: 'ORDEM DOS MÉDICOS DE MOÇAMBIQUE',
  subInstitution: 'COLÉGIO DE NEUROCIRURGIA',
  hospital: 'HOSPITAL CENTRAL DE NAMPULA',
  service: 'SERVIÇO DE NEUROCIRURGIA',
  tipoEvento: 'Jornadas Científicas do Hospital Central de Nampula',

  nome: 'Armando Manuel Sitoe',
  nid: '10482910',
  sexo: 'Masculino',
  idade: '45 anos',
  raca: 'Negra',
  estadoCivil: 'Casado',
  naturalidade: 'Xai-Xai, Gaza',
  residencia: 'Bairro de Chamanculo C, Casa 42, Maputo',
  profissao: 'Mecânico Auto',
  localTrabalho: 'Oficina Central de Transportes',
  provenienteDe: 'Hospital Geral José Macamo',
  emData: '24/09/2026 14:30',
  historiaFornecidaPor: 'Próprio paciente e esposa (fiável)',
  servicoProveniencia: 'Banco de Socorros / Medicina',

  motivoInternamento: 'Cefaleia holocraniana intensa progressiva com vómitos em jato e hemiparesia esquerda de instalação há 5 dias.',
  historiaDoencaActual: 'Paciente masculino de 45 anos, previamente hígido, com início há cerca de 3 semanas de cefaleia holocraniana, de agravamento matinal, inicialmente aliviada com paracetamol. Há 5 dias refere intensificação marcada da dor, refratária a analgésicos comuns, associada a episódios de vómitos alimentares em jato (sem náuseas prévias) e desvio da comissura labial para a direita com perda progressiva de força no hemicorpo esquerdo. Nega febre, crises convulsivas prévias, traumatismo craniano recente ou perda ponderal abrupta. Foi transferido do HG José Macamo após estabilização inicial com dexametasona e manitol EV.',

  revisaoSistemas: {
    respiratorio: {
      tosse: { checked: false, observation: '' },
      expectoracao: { checked: false, observation: '' },
      dorToracica: { checked: false, observation: '' },
      dispneia: { checked: false, observation: '' },
      dpnOrtopneia: { checked: false, observation: '' },
      palpitacoes: { checked: false, observation: '' },
      suoresNocturnos: { checked: false, observation: '' },
      pieira: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
    },
    sistemaNervoso: {
      convulsoes: { checked: false, observation: '' },
      sincope: { checked: false, observation: '' },
      cefaleias: { checked: true, observation: 'Holocraniana, pulsátil, matinal severa (EVA 9/10)' },
      disturbiosVisuais: { checked: true, observation: 'Visão turva binocular intermitente' },
      disturbiosSensibilidade: { checked: true, observation: 'Hipoestesia tátil e dolorosa no hemicorpo esquerdo' },
      fraquezaMuscular: { checked: true, observation: 'Diminuição da força no MSE e MIE' },
      outros1: { checked: false, observation: '' },
      outros2: { checked: false, observation: '' },
    },
    gastrointestinal: {
      vomitos: { checked: true, observation: 'Em jato, 3-4 episódios/dia' },
      hematemeses: { checked: false, observation: '' },
      obstipacao: { checked: false, observation: '' },
      pirose: { checked: false, observation: '' },
      enfartamentoPosPrandial: { checked: false, observation: '' },
      flatulencia: { checked: false, observation: '' },
      dorAbdominal: { checked: false, observation: '' },
      ictericia: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
      outros2: { checked: false, observation: '' },
    },
    genitourinario: {
      disuria: { checked: false, observation: '' },
      polaquiuria: { checked: false, observation: '' },
      hematuria: { checked: false, observation: '' },
      incontinenciaUrinaria: { checked: false, observation: '' },
      corrimentoUretralVaginal: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
    },
    hemolinfopoetico: {
      anomaliasCoagulacao: { checked: false, observation: '' },
      anemias: { checked: false, observation: '' },
      outros1: { checked: false, observation: '' },
    },
    caracterizacaoSintomas: 'Sintomatologia de Hipertensão Intracraniana (cefaleia + vómitos em jato + edema de papila) associada a sinais focais de hemisfério direito (hemiparesia facio-braquio-crural esquerda).',
  },

  historiaPregressa: 'Hipertensão arterial diagnosticada há 2 anos, com adesão irregular a Enalapril 10mg/dia. Nega diabetes mellitus, tuberculose ou asma. Cirurgia prévia: apendicectomia aos 18 anos sem intercorrências. Alergias medicamentosas desconhecidas. Sem antecedentes de DTS.',
  historiaPessoalSocial: 'Habitação de alvenaria em zona periurbana com água canalizada e energia eléctrica da rede. Não fumador. Consumo social de álcool aos fins de semana (cerveja). Mecânico há 20 anos, contacto com óleos e solventes. Nega viagens internacionais recentes.',
  historiaGinecoObstetrica: 'Não aplicável (sexo masculino).',
  historiaFamiliar: 'Pai falecido aos 68 anos de acidente vascular cerebral. Mãe viva de 70 anos com hipertensão arterial controlada. 2 irmãos saudáveis. Sem história conhecida de neoplasias no sistema nervoso central.',

  estadoGeral: 'Paciente em estado geral moderado, consciente, acamado, vigil, algo sonolento mas facilmente despertável.',
  idadeAparente: 'Compatível com a idade cronológica.',
  glasgowOcular: '4',
  glasgowVerbal: '5',
  glasgowMotor: '5',
  glasgowTotal: '14',
  pele: 'Corada, elástica, sem lesões cutâneas atípicas ou estigmas de neurofibromatose.',
  mucosas: 'Normocoradas e húmidas.',
  edemas: 'Ausência de edemas periféricos.',
  linfadenopatia: 'Sem adenomegalias palpáveis cervicais, axilares ou inguinais.',
  frequenciaCardiaca: '64 bpm (ritmo sinusal regular)',
  frequenciaRespiratoria: '16 cpm',
  pulsoRadial: 'Cheio, rítmico, simétrico',
  tensaoArterial: '150/95 mmHg',
  temperaturaAxilar: '36.6 ºC',
  spO2: '98% em ar ambiente',
  peso: '74 kg',
  altura: '1.72 m',
  imc: '25.0 kg/m²',
  outrosExameGeral: 'Boa perfusão capilar periférica (< 2s).',

  cabecaFacies: 'Fácies atípica, ligeira assimetria facial evidente com desvio da comissura labial para a direita.',
  cabecaOlhos: 'Pupilas isocóricas, fotoreactivas à luz directa e consensual (3mm). Sem exoftalmia.',
  cabecaNariz: 'Fossas nasais pérvias, sem epistaxe ou rinoliquorreia.',
  cabecaBoca: 'Higiene razoável, dentição conservada, sem lesões na mucosa jugal.',
  cabecaOrofaringe: 'Úvula centrada à fonação, pilares amigdalinos sem hipertrofia ou exsudados.',
  cabecaOuvidos: 'Condutos auditivos externos livres, sem otorragia ou otoliquorreia.',
  cabecaOutros: 'Perímetro cefálico: 57 cm. Sem deformidades ou depressões ósseas palpáveis.',

  pescocoForma: 'Cilíndrico, simétrico.',
  pescocoDimensoes: 'Normotrófico.',
  pescocoMobilidade: 'Conservada em todos os eixos, sem dor à mobilização passiva.',
  pescocoPosicaoTraqueia: 'Centrada na linha média.',
  pescocoPVJ: 'Sem turgência jugular a 45º.',
  pescocoTiroide: 'Não palpável, indolor e sem nódulos.',
  pescocoOutros: 'Sem sopros carotídeos audíveis.',

  semiologiaRespInspecao: 'Tórax simétrico, expansibilidade conservada, sem tiragem intercostal.',
  semiologiaRespPalpacao: 'Frémito tóraco-vocal universalmente mantido e simétrico.',
  semiologiaRespPercussao: 'Som claro pulmonar em ambos os campos pulmonares.',
  semiologiaRespAuscultacao: 'Murmúrio vesicular universalmente mantido, sem ruídos adventícios.',

  semiologiaCardInspecao: 'Ápice não visível, sem impulsões para-esternais anómalas.',
  semiologiaCardPalpacao: 'Choque da ponta palpável no 5º espaço intercostal esquerdo na linha hemiclavicular.',
  semiologiaCardPercussao: 'Área de macicez cardíaca dentro dos limites anatómicos normais.',
  semiologiaCardAuscultacao: 'Sons cardíacos rítmicos, 2 tempos bem timbrados, sem sopros audíveis.',

  mamasAxilasInspecao: 'Mamas masculinas normotróficas, sem nódulos, ginecomastia ou lesões.',
  mamasAxilasPalpacao: 'Sem linfadenopatias axilares palpáveis bilaterais.',

  abdomenInspecao: 'Plano, simétrico, cicatriz de apendicectomia antiga na FID bem consolidada.',
  abdomenPalpacao: 'Mole, depressível, indolor à palpação superficial e profunda, sem organomegalias.',
  abdomenPercussao: 'Timpanismo abdominal fisiológico conservado, macicez hepática normal.',
  abdomenAuscultacao: 'Ruídos hidroaéreos presentes e normoactivos nos quatro quadrantes.',
  abdomenManobras: 'Murphy e Blumberg negativos. Sem massas abdominais ou herniações.',

  genitaisInspecao: 'Genitais externos masculinos com características de adulto, sem lesões cutâneas.',
  genitaisPalpacao: 'Testículos tópicos nas bolsas escrotais, sem massas ou dor à palpação.',
  genitaisPercussao: 'Sem globo vesical palpável.',
  genitaisAuscultacao: 'Sem sopros nas artérias ilíacas ou femorais.',
  genitaisUrina: 'Urina límpida, coloração amarelo-âmbar, débito urinário preservado.',

  proctologicoPosicao: 'Decúbito lateral esquerdo (posição de Sims).',
  proctologicoInspecao: 'Região perianal sem fístulas, fissuras ou hemorroidas externas.',
  proctologicoPalpacao: 'Tónus do esfíncter anal preservado. Próstata aumentada grau I, consistência fibroelástica, superfície lisa e indolor.',

  ginecologicoPosicao: 'Não aplicável (sexo masculino).',
  ginecologicoInspecao: 'Não aplicável.',
  ginecologicoPalpacao: 'Não aplicável.',

  membrosSupInspecao: 'Simétricos, sem atrofias musculares ou deformidades osteoarticulares.',
  membrosSupPalpacao: 'Pulsos radiais e braquiais cheios e simétricos. Sem dor à palpação articular.',
  membrosSupAuscultacao: 'Sem sopros vasculares.',
  membrosSupManobras: 'Queda do membro superior esquerdo na prova de Mingazzini.',

  membrosInfInspecao: 'Sem edema maleolar, sem varizes ou alterações tróficas da pele.',
  membrosInfPalpacao: 'Pulsos pediosos e tibiais posteriores palpáveis e simétricos. Sem empastamento gemelar.',
  membrosInfAuscultacao: 'Sem sopros femorais audíveis.',
  membrosInfManobras: 'Queda do membro inferior esquerdo na prova de Barré.',

  estadoMental: 'Orientado no tempo, espaço e na própria pessoa. Atenção e memória recente ligeiramente lentificadas, sem alucinações ou delírios.',
  linguagem: 'Compreensão e fluência verbais conservadas, sem disartria ou afasia motora/sensitiva.',
  par1: 'Olfato preservado em ambas as narinas (testado com substância não irritante).',
  par2: 'Acuidade visual grosseiramente mantida em ambos os olhos. Campimetria por confrontação com ligeira hemianópsia homónima esquerda.',
  fundoscopia: 'Edema de papila bilateral incipiente com apagamento dos bordos do disco óptico, sem hemorragias retinianas.',
  pares3_4_6: 'Movimentos oculares extrínsecos preservados, sem diplopia ou nistagmo.',
  par5: 'Sensibilidade facial diminuída no hemicorpo esquerdo (V1, V2 e V3). Reflexo corneano atenuado à esquerda.',
  par7: 'Parésia facial central esquerda com apagamento do sulco nasogeniano esquerdo e desvio labial.',
  par8: 'Audição mantida bilateralmente (teste de voz cochichada normal). Weber indiferenciado.',
  pares9_10: 'Reflexo de vómito presente e simétrico. Deglutição preservada, voz sem rouquidão.',
  par11: 'Força na rotação cefálica e elevação de ombros mantida bilateralmente (esternocleidomastóideo e trapézio grau 5/5).',
  par12: 'Língua centrada na protusão, sem fasciculações ou atrofia.',
  tonusMuscular: 'Ligeira hipertonia espástica no hemicorpo esquerdo (membro superior flexor e membro inferior extensor).',
  forcaMuscular: 'Hemiparesia facio-braquio-crural esquerda proporcional. Força muscular: Hemisfério direito normal (5/5); MSE grau 3/5; MIE grau 4/5.',
  coordenacaoMarcha: 'Marcha helicópode ou ceifante à esquerda. Prova índice-nariz e calcanhar-joelho com dismetria discreta à esquerda secundária à paresia.',
  sensibilidade: 'Hipoestesia táctil e dolorosa no hemicorpo esquerdo. Propriocepção consciente conservada.',
  reflexos: 'Hiperreflexia miotática osteotendinosa à esquerda (bicipital, tricipital, patelar e aquileu +++/+). Sinal de Babinski positivo à esquerda, Hoffmann positivo à esquerda.',
  sinaisMeningeos: 'Rigidez da nuca ausente. Sinais de Kernig e Brudzinski negativos.',

  resumo: 'Paciente do sexo masculino, 45 anos, com síndrome de hipertensão intracraniana (cefaleia matinal severa, vómitos em jato, papiledema bilateral) de evolução subaguda (3 semanas) e síndrome deficitário piramidal (hemiparesia facio-braquio-crural esquerda espástica, Babinski à esquerda) de início há 5 dias. O quadro aponta para processo expansivo intracraniano hemisférico supratentorial direito (lobo fronto-parietal).',

  diagnosticosSindromicos: '1. Síndrome de Hipertensão Intracraniana\n2. Síndrome Piramidal / Hemiparético Esquerdo\n3. Síndrome de Compressão Fronto-Parietal Direita',
  diagnosticosEtiologicos: '1. Neoplasia Primária do Sistema Nervoso Central (Glioblastoma vs. Astrocitoma de Alto Grau)\n2. Metástase Cerebral Única (a descartar primário pulmonar/GI)\n3. Abcesso Cerebral Fronto-Parietal Direito (menos provável pela ausência de febre)',
  diagnosticosTopograficos: 'Região intra-axial fronto-parietal direita (cortical e subcortical), com efeito de massa sobre os gânglios da base e linha média.',

  meiosAuxiliares: '1. Tomografia Axial Computorizada (TAC) Crânio-encefálica com contraste: urgente para avaliar lesão expansiva, edema perilesional e desvio das estruturas da linha média.\n2. Ressonância Magnética (RM) Cerebral com espectroscopia e perfusão: para delimitação anatómica precisa e caracterização tecidular pré-cirúrgica.\n3. Radiografia do Tórax (RX Tórax PA): rastreio de lesão primária pulmonar ou foco infeccioso.\n4. Hemograma completo, coagulograma (TP, INR, TTPA), ionograma, ureia e creatinina: avaliação pré-operatória.',
  attachedImages: [
    {
      id: 'sample-tac-1',
      type: 'TAC',
      fileName: 'TAC_Cranio_Axial_Contraste.jpg',
      examDate: '2026-09-24',
      notes: 'TAC Crânio Axial com contraste evidenciando volumosa lesão expansiva fronto-parietal direita (aprox. 4.8 x 4.2 cm), com realce periférico anelar irregular, halo de edema vasogénico circundante e desvio de estruturas da linha média de 7mm para a esquerda.',
      dataUrl: sampleTacDataUrl,
    },
    {
      id: 'sample-rx-1',
      type: 'RX',
      fileName: 'RX_Torax_PA.jpg',
      examDate: '2026-09-24',
      notes: 'Radiografia do Tórax em incidência postero-anterior (PA): Parênquima pulmonar sem lesões nodulares, massas ou infiltrados consolidados evidentes. Seios costofrénicos livres. Índice cardiotorácico dentro dos limites fisiológicos.',
      dataUrl: sampleRxDataUrl,
    },
  ],

  diagnosticosDiferenciais: '1. Glioblastoma Multiforme (GBM): lesão heterogénea em homem de meia-idade com rápida progressão.\n2. Metástase Intracraniana isolada: curso clínico compatível com hipertensão intracraniana e efeito de massa.\n3. Astrocitoma Anaplásico (Grau III): lesão glial infiltrativa de crescimento subagudo.\n4. Abcesso Cerebral: mesmo sem febre actual, pode mimetizar lesão tumoral anelar.\n5. Hematoma Subdural Crónico / Subagudo: considerar mesmo sem história de TCE bem documentado.',

  diagnosticosDefinitivos: 'Processo Expansivo Intracraniano Parieto-frontal Direito com Edema Vasogénico e Efeito de Massa (suspeita de Neoplasia Glial de Alto Grau).',
  propostaTerapeutica: '1. Medidas Anti-edema Cerebral: Dexametasona 4mg IV de 6/6h + Omeprazol 40mg IV/dia para gastroprotecção.\n2. Anticonvulsivante profilático: Levetiracetam 500mg VO de 12/12h.\n3. Cabeceira elevada a 30 graus, manutenção da euvolemia e monitorização neurológica contínua.\n4. Proposta Cirúrgica: Craniotomia osteoplástica fronto-parietal direita para ressecção microcirúrgica máxima segura da lesão e envio para exame histopatológico.',
  prognostico: 'Reservado a curto e médio prazo, condicionado à histopatologia definitiva e ao grau de ressecção cirúrgica obtido.',

  elaboradoPor: 'Dr. Lucas Nhantumbo',
  mrNc: 'Médico Residente de Neurocirurgia / OMM nº 4981',
  corrigidoPor: 'Dr. Pedro Macuácua - Especialista em Neurocirurgia',
  comentariosFinais: 'Doente admitido na enfermaria de Neurocirurgia. TAC craniana realizada confirma volumosa massa heterogénea fronto-parietal direita com captação anelar de contraste e desvio da linha média de 7mm. Programar cirurgia para a próxima sessão de bloco operatório.',
};
